name: task_ropulva_todo_app
description: "Technical Assessment"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.35
  just_audio_windows: ^0.2.0  # Add Windows support
  audio_session: ^0.1.18  # Add this for better audio handling
  # Provides iOS-style icons for Flutter apps
  cupertino_icons: ^1.0.8
  # Allows using Google Fonts in Flutter apps
  google_fonts: ^6.2.1
  # Persistent storage for simple data
  shared_preferences: ^2.3.3
  window_manager: ^0.3.8  # Replace window_size with window_manager
  flutter_animate: ^4.5.2
  connectivity_plus: ^6.1.0
  firebase_core: ^3.8.1
  hive: ^2.2.3
  path_provider: ^2.1.5
  hive_flutter: ^1.1.0
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.4
  get_it: ^8.0.2
  equatable: ^2.0.7
  bloc: ^8.1.4
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6
  package_info_plus: ^4.1.0  # or the latest version
  flutter_svg: ^2.0.16
  flutter_sound: ^9.17.8
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Provides recommended set of lints for Flutter apps
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/lotties/
    - assets/images/
    - assets/sound/
    - assets/sound/crowd-cheer-in-school-auditorium-236699.mp3

